// <auto-generated />
using Infosys.PaymentMicroservice.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infosys.PaymentMicroservice.Migrations
{
    [DbContext(typeof(PaymentDBContext))]
    [Migration("20260129105532_CreateNewPaymentDB")]
    partial class CreateNewPaymentDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Infosys.PaymentMicroservice.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PaymentId");

                    b.ToTable("Payments", t =>
                        {
                            t.HasCheckConstraint("chk_PaymentStatus", "PaymentStatus IN ('Confirmed', 'Not Confirmed')");
                        });

                    b.HasData(
                        new
                        {
                            PaymentId = 1,
                            BookingId = 4002,
                            PaymentStatus = "Confirmed",
                            TotalAmount = 200000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
